export const introduction = {
    "title": "Hello there! Remco here",
    "content": "This is a sample project generated by the Bento CLI. It demonstrates the use of Bento's built-in features and tools. The project is structured in a way that is easy to understand and extend. It is a great starting point for building your next project.",
    "button": "More about me"
}